---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mas-fvt-core
spec:
  params:
    # Test Container Information
    # -------------------------------------------------------------------------
    - name: fvt_image_registry
      type: string
      description: FVT Container Image Registry (required)
    - name: fvt_image_version
      type: string
      description: FVT Container Image Version
      default: latest

    # Test Framework Information
    # -------------------------------------------------------------------------
    - name: test_suite
      type: string
      description: If the FVT container image contains multiple suites, use this to control the suite that will be executed
      default: ""
    - name: fvt_enable_debug
      type: string
      description: Turn on debug logging (verbose mode)
      default: "true"

    - name: devops_mongo_uri
      type: string
      description: Mongo URI for recording test results (optional)
      default: ""
    - name: devops_build_number
      type: string
      description: Build number to record test result (optional)
      default: ""

    - name: product_channel
      type: string
      description: "Subscription channel for the product (todo: have the test code look this up instead)"
      default: ""

    - name: mas_instance_id
      type: string
      description: Instance ID of the target test environment
    - name: mas_workspace_id
      type: string
      description: Workspace ID in MAS to use for running the tests

    # Test-specific Information (all optional)
    # -------------------------------------------------------------------------
    - name: ddp_apikey
      type: string
      description: Partium username (required by fvt-adoptionusagereporter)
      default: ""
    - name: partium_username
      type: string
      description: Partium username (required by fvt-coreapi-workspacemgmt)
      default: ""
    - name: partium_password
      type: string
      description: Partium password (required by fvt-coreapi-workspacemgmt)
      default: ""

  stepTemplate:
    name: 'fvt-core'
    env:
      # What are we testing?
      - name: PRODUCT_ID
        value: ibm-mas
      - name: PRODUCT_CHANNEL
        value: $(params.product_channel)
      - name: NAMESPACE
        value: "mas-$(params.mas_instance_id)-core"
      - name: INSTANCE_ID
        value: "$(params.mas_instance_id)"
      - name: WORKSPACE_ID
        value: "$(params.mas_workspace_id)"

      # Enable results to be saved
      - name: DEVOPS_MONGO_URI
        value: $(params.devops_mongo_uri)
      - name: BUILD_NUM
        value: $(params.devops_build_number)

      # The name of the test suite inside the container we will execute (/opt/ibm/test/suites/{TEST_SUITE})
      - name: TEST_SUITE
        value: $(params.test_suite)

      # Set the logging level to debug if this is set to true
      - name: FVT_ENABLE_DEBUG
        value: "$(params.fvt_enable_debug)"

      # Parameters for tests
      - name: IBMADMIN_ENABLED
        value: "true"

      - name: DDP_APIKEY
        value: $(params.ddp_apikey)
      - name: PARTIUM_USERNAME
        value: $(params.partium_username)
      - name: PARTIUM_PASSWORD
        value: $(params.partium_password)
  steps:
    - image: '$(params.fvt_image_registry)/mas-devops/fvt-ibm-mas:$(params.fvt_image_version)'
      imagePullPolicy: IfNotPresent
      timeout: 90m # Ensure bad FVTs don't run forever
      onError: continue # Ensure bad FVTs don't break the pipeline
      resources: {}
      workingDir: /opt/ibm/test/src
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory

  workspaces:
    - name: configs
