---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mas-devops-nvidia-gpu
spec:
  params:
    # Control the image pull policy for the CLI container image
    - name: image_pull_policy
      type: string
      default: IfNotPresent

    # Optional support built into the ansible-devops image
    # for saving task execution results to a MongoDb instance
    - name: mas_instance_id
      type: string
      description: Optional MAS instance Id, used to enable save-junit-to-mongo.py
      default: ""
    - name: devops_mongo_uri
      type: string
      description: Optional MongoDb connection URI, used to enable save-junit-to-mongo.py
      default: ""
    - name: devops_suite_name
      type: string
      description: Optional name for the junit suite, used to enable save-junit-to-mongo.py
      default: ""
    - name: devops_build_number
      type: string
      description: Optional identifier for the execution run, used to enable save-junit-to-mongo.py
      default: ""

    - name: gpu_namespace
      type: string
      description: Optional. Nvidia gpu namespace
      default: ""
    - name: gpu_channel
      type: string
      description: Optional. Nvidia gpu channel for install and updates
      default: ""
    - name: nfd_namespace
      type: string
      description: Optional. Node feature discovery namespace
      default: ""
    - name: nfd_channel
      type: string
      description: Optional. Node feature discovery channel for install and updates
      default: ""

  stepTemplate:
    env:
      # Optional support built into the ansible-devops image
      # for saving task execution results to a MongoDb instance
      - name: MAS_INSTANCE_ID
        value: $(params.mas_instance_id)
      - name: DEVOPS_MONGO_URI
        value: $(params.devops_mongo_uri)
      - name: DEVOPS_SUITE_NAME
        value: $(params.devops_suite_name)
      - name: DEVOPS_BUILD_NUMBER
        value: $(params.devops_build_number)

      - name: GPU_NAMESPACE
        value: $(params.gpu_namespace)
      - name: GPU_CHANNEL
        value: $(params.gpu_channel)
      - name: NFD_NAMESPACE
        value: $(params.nfd_namespace)
      - name: NFD_CHANNEL
        value: $(params.nfd_channel)

  steps:
    - name: nvidia-gpu
      command:
        - /opt/app-root/src/run-role.sh
        - nvidia_gpu
      image: quay.io/ibmmas/cli:latest
      imagePullPolicy: $(params.image_pull_policy)
      workingDir: /workspace/configs

  workspaces:
    - name: configs
