---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mas-devops-suite-upgrade
spec:
  params:
    - name: cli_version
      type: string
      default: latest

    - name: mas_instance_id
      type: string
      description: Instance ID
    - name: mas_channel
      type: string
      description: MAS Channel

  stepTemplate:
    env:
      - name: MAS_INSTANCE_ID
        value: $(params.mas_instance_id)
      - name: MAS_CHANNEL
        value: $(params.mas_channel)
  steps:
    - name: suite-upgrade
      command:
        - /opt/app-root/src/run-role.sh
        - suite_upgrade
      image: quay.io/ibmmas/cli:$(params.cli_version)
      imagePullPolicy: IfNotPresent
