---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mas-devops-suite-app-upgrade
spec:
  params:
    - name: cli_version
      type: string
      default: latest

    - name: mas_instance_id
      type: string
      description: Instance ID
    - name: mas_app_id
      type: string
      description: Maximo Application Suite Application ID
    - name: mas_app_channel
      type: string
      description: Instance ID

  stepTemplate:
    env:
      - name: MAS_INSTANCE_ID
        value: $(params.mas_instance_id)
      - name: MAS_APP_ID
        value: $(params.mas_app_id)
      - name: MAS_APP_CHANNEL
        value: $(params.mas_app_channel)
  steps:
    - name: suite-app-upgrade
      command:
        - /opt/app-root/src/run-role.sh
        - suite_app_upgrade
      image: quay.io/ibmmas/cli:$(params.cli_version)
      imagePullPolicy: IfNotPresent
