apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mas-cli
  name: mas-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mas-cli
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mas-cli
    spec:
      containers:
      - name: mas-cli
        imagePullPolicy: IfNotPresent
        image: quay.io/ibmmas/cli:latest
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
