---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gitops-create-mongo-user
spec:
  params:
    - name: cluster_name
      type: string
    - name: account
      type: string
    - name: secrets_path
      type: string
    - name: avp_aws_secret_region
      type: string
    - name: avp_aws_secret_key
      type: string
    - name: avp_aws_access_key
      type: string
    - name: mas_instance_id
      type: string
    - name: vpc_id
      type: string
    - name: vpc_ipv4_cidr
      type: string
    - name: mongo_provider
      type: string
      default: aws
    - name: aws_key_pair_name
      type: string
      default: sre-key-pair
  stepTemplate:
    name: gitops-create-mongo-user
    env:
      - name: CLUSTER_NAME
        value: $(params.cluster_name)
      - name: ACCOUNT
        value: $(params.account)
      - name: SECRET_PATH
        value: $(params.secrets_path)
      - name: SM_AWS_REGION
        value: $(params.avp_aws_secret_region)
      - name: SM_AWS_SECRET_ACCESS_KEY
        value: $(params.avp_aws_secret_key)
      - name: SM_AWS_ACCESS_KEY_ID
        value: $(params.avp_aws_access_key)
      - name: MAS_INSTANCE_ID
        value: $(params.mas_instance_id)
      - name: VPC_ID
        value: $(params.vpc_id)
      - name: VPC_IPV4_CIDR
        value: $(params.vpc_ipv4_cidr)
      - name: MONGO_PROVIDER
        value: $(params.mongo_provider)
      - name: AWS_KEY_PAIR_NAME
        value: $(params.aws_key_pair_name)
  steps:
    - args:
      - |-
        mas gitops-create-mongo-user -a $ACCOUNT -c $CLUSTER_NAME -m $MAS_INSTANCE_ID \
        --secrets-path $SECRET_PATH \
        --mongo-provider $MONGO_PROVIDER \
        --aws-region $SM_AWS_REGION \
        --aws-secret-key $SM_AWS_SECRET_ACCESS_KEY \
        --aws-access-key $SM_AWS_ACCESS_KEY_ID \
        --aws-vpc-id $VPC_ID \
        --aws-docdb-cluster-name docdb-$CLUSTER_NAME \
        --aws-docdb-ingress-cidr $VPC_IPV4_CIDR \
        --aws-docdb-egress-cidr $VPC_IPV4_CIDR \
        --aws-ec2-cidr-az1 10.0.0.0/17 \
        --aws-key-pair-name $AWS_KEY_PAIR_NAME
      command:
        - /bin/sh
        - -c
      name: gitops-create-mongo-user
      imagePullPolicy: Always
      image: quay.io/ibmmas/cli:6.4.0-pre.gitops
  workspaces:
    - name: configs
